= GitHub Webhook

GitHub Webhook app. Receives messages from GitHub and sends them to a message broker. Part of the deployment pipeline example

== Docker integration

For more information please read the https://spring.io/guides/gs/spring-boot-docker/[guides].

=== Building docker image

```bash
$  ./mvnw package docker:build
```

=== Setting authentication for Docker

Go to your `~/.m2/settings.xml` and add the server with id `docker-repo`

```xml
<server>
  <id>docker-repo</id>
  <username>username</username>
  <password>password</password>
  <configuration>
    <email>your@email.com</email>
  </configuration>
</server>
```

=== Pushing docker image

IMPORTANT: Remember to set authentication in your `settings.xml`

```bash
$  ./mvnw package docker:build -DpushImage
```

or

```bash
$  ./mvnw deploy
```

== Running the application in Kubernetes

- First create and push the docker image
+
```bash
$ ./mvnw package docker:build -DpushImage
```
- Start `minikube`
+
```bash
$ minikube start
```
- Start Kubernetes Dashboard
+
```bash
$ minikube dashboard
```
- Create this deployment on the cluster using kubectl
+
```bash
$ kubectl create -f deployment.yml
```
- Check if deployment is there
+
```bash
kubectl describe deployment github-webhook-deployment
```
- Create a service to expose the pod to the outside world
+
```bash
$ kubectl create -f service.yml
```
- Check if service has properly been created
+
```bash
$ kubectl describe service github-webhook-service
```
- Retrieve the URL from minikube
+
```bash
$ minikube service github-webhook-service --url
```
- Or go directly to the URL
+
```bash
$ minikube service github-webhook-service
```

== Deleting deployments / services

It's enough to call `kubectl delete` to delete deployment / service

```bash
$ kubectl delete deployment github-webhook-deployment
$ kubectl delete service github-webhook-service
```